/*
nome: Gustavo Mirabal Czarnotta
RA: 2678098
estrutura funcionario
 cadeia nome, endereco
 real salario
fimestrutura
início
 funcionario f
 funcionario.nome <- “Miguel”
 funcionario.endereco <- “Rua A”
 funcionario.salario <- 3000
 escreva(“Nome:”, funcionario.nome)
 escreva(“Endereço:”, funcionario.endereco)
 escreva(“Salário:”, funcionario.salario)
fim

R: o erro esta na linha 6 a 9, pois funcionario é o tipo da variavel e não a variavel em si.

*/